import Anthropic from '@anthropic-ai/sdk';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import pino from 'pino';
import config from './config.js';
import { toolDefinitions, handleTool } from './tools.js';
import { getTasteProfile } from './tt-api.js';

const log = pino({ name: 'claude' });

// Backend: MiniMax M2.7 via its Anthropic-compatible endpoint.
// The @anthropic-ai/sdk works unchanged — only baseURL + apiKey + model name change.
// Falls back to real Anthropic if MINIMAX_API_KEY is absent (dev/rollback).
const useMinimax = !!config.minimaxApiKey;
const client = new Anthropic({
  apiKey: useMinimax ? config.minimaxApiKey : config.anthropicApiKey,
  baseURL: useMinimax ? 'https://api.minimax.io/anthropic' : undefined,
});
const MODEL = useMinimax ? 'MiniMax-M2.7' : 'claude-sonnet-4-6';
log.info({ backend: useMinimax ? 'minimax' : 'anthropic', model: MODEL }, 'LLM backend');

// ─── System prompt assembly ─────────────────────────────────────────────────
// The bot's self-awareness doc lives in CLAUDE.md alongside this file. It is
// edited by humans (and auto-regenerated by scripts/regen-bot-docs.mjs for the
// tool inventory section). Loaded once at boot — a restart is required to pick
// up edits, which is fine because deploys restart the systemd unit anyway.

const HERE = dirname(fileURLToPath(import.meta.url));
const CLAUDE_MD_PATH = join(HERE, 'CLAUDE.md');

let BASE_PROMPT;
try {
  BASE_PROMPT = readFileSync(CLAUDE_MD_PATH, 'utf-8');
  log.info({ path: CLAUDE_MD_PATH, chars: BASE_PROMPT.length }, 'loaded bot self-awareness doc');
} catch (e) {
  log.error({ err: e.message, path: CLAUDE_MD_PATH }, 'CLAUDE.md missing — falling back to minimal prompt');
  BASE_PROMPT =
    'You are Taste Trawler, a resale assistant for MG. Be concise. No emoji. Never write to Vinted.';
}

// Taste profile is refreshed lazily — cached per process for 30 minutes so we
// don't hammer the web app on every message, but still stay fresh over a day.
const TASTE_TTL_MS = 30 * 60 * 1000;
let tasteCache = { profile: null, fetchedAt: 0 };

async function getCachedTasteProfile() {
  const now = Date.now();
  if (tasteCache.profile && now - tasteCache.fetchedAt < TASTE_TTL_MS) {
    return tasteCache.profile;
  }
  try {
    const profile = await getTasteProfile();
    tasteCache = { profile, fetchedAt: now };
    return profile;
  } catch (e) {
    log.warn({ err: e.message }, 'taste profile fetch failed — using stale/none');
    return tasteCache.profile; // may be null — caller tolerates
  }
}

function formatTasteProfile(p) {
  if (!p || !p.totalSold) return '';
  const parts = [];
  parts.push(`## Live taste profile (MG's resale history, ${p.totalSold} sold items)`);
  if (p.avgMargin) parts.push(`- Average margin per sale: £${(p.avgMargin / 100).toFixed(2)}`);
  if (p.avgDaysToSell) parts.push(`- Average days to sell: ${p.avgDaysToSell}`);
  if (p.topBrands?.length) {
    parts.push(
      `- Top brands: ${p.topBrands
        .map((b) => `${b.brand} (${b.count}, £${(b.avgMargin / 100).toFixed(2)} avg)`)
        .join(', ')}`,
    );
  }
  if (p.topCategories?.length) {
    parts.push(
      `- Top categories: ${p.topCategories
        .map((c) => `${c.category} (${c.count}, £${(c.avgMargin / 100).toFixed(2)} avg)`)
        .join(', ')}`,
    );
  }
  if (p.topColours?.length) {
    parts.push(`- Top colours: ${p.topColours.map((c) => `${c.colour} ${c.pct}%`).join(', ')}`);
  }
  if (p.topStyleTags?.length) {
    parts.push(`- Recurring style tags: ${p.topStyleTags.map((t) => t.tag).join(', ')}`);
  }
  return parts.join('\n');
}

async function buildSystemPrompt() {
  const taste = formatTasteProfile(await getCachedTasteProfile());
  return taste ? `${BASE_PROMPT}\n\n${taste}` : BASE_PROMPT;
}

// ─── Chat loop ──────────────────────────────────────────────────────────────

/**
 * Merge adjacent same-role messages. The Anthropic (and MiniMax-compat) API
 * requires strictly alternating user/assistant turns, but our DB now logs
 * every group-chat line as role='user' regardless of who sent it — including
 * untriggered chatter between MG and James. Collapse runs of the same role
 * into a single message with newline-joined content so the API accepts it.
 *
 * Tool-result turns (content = array of blocks) are left intact; they only
 * appear inside the tool loop below, not in DB history.
 */
function collapseRoles(msgs) {
  const out = [];
  for (const m of msgs) {
    const prev = out[out.length - 1];
    if (prev && prev.role === m.role && typeof prev.content === 'string' && typeof m.content === 'string') {
      prev.content = `${prev.content}\n${m.content}`;
    } else {
      out.push({ role: m.role, content: m.content });
    }
  }
  return out;
}

export async function chat(messages, imageUrls = []) {
  const anthropicMessages = collapseRoles(messages);

  // Legacy path: if images come through as URLs (not pre-analysed VLM text),
  // attach them to the last user message. With MiniMax M2.7 this path is
  // unused — index.js pre-analyses via VLM and injects text instead.
  if (imageUrls.length > 0) {
    const lastMsg = anthropicMessages[anthropicMessages.length - 1];
    if (typeof lastMsg.content === 'string') {
      lastMsg.content = [
        ...imageUrls.map((url) => ({ type: 'image', source: { type: 'url', url } })),
        { type: 'text', text: lastMsg.content || 'What do you think of this?' },
      ];
    }
  }

  const systemPrompt = await buildSystemPrompt();

  let response = await client.messages.create({
    model: MODEL,
    max_tokens: 2048,
    system: systemPrompt,
    tools: toolDefinitions,
    messages: anthropicMessages,
  });

  // Tool loop — max 5 iterations
  let iterations = 0;
  while (response.stop_reason === 'tool_use' && iterations < 5) {
    iterations++;
    const toolBlocks = response.content.filter((b) => b.type === 'tool_use');
    const toolResults = [];

    for (const block of toolBlocks) {
      log.info({ tool: block.name, input: block.input }, 'tool call');
      try {
        const result = await handleTool(block.name, block.input);
        toolResults.push({ type: 'tool_result', tool_use_id: block.id, content: result });
      } catch (err) {
        log.error({ tool: block.name, err: err.message }, 'tool error');
        toolResults.push({
          type: 'tool_result',
          tool_use_id: block.id,
          content: `Error: ${err.message}`,
          is_error: true,
        });
      }
    }

    anthropicMessages.push({ role: 'assistant', content: response.content });
    anthropicMessages.push({ role: 'user', content: toolResults });

    response = await client.messages.create({
      model: MODEL,
      max_tokens: 2048,
      system: systemPrompt,
      tools: toolDefinitions,
      messages: anthropicMessages,
    });
  }

  const textBlocks = response.content.filter((b) => b.type === 'text');
  return textBlocks.map((b) => b.text).join('\n');
}
